# Generated by Django 6.0.2 on 2026-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('lehenga', 'Lehenga'), ('kurti', 'Kurti'), ('saree', 'Saree'), ('gown', 'Gown')], default='kurti', max_length=20),
        ),
    ]
