# Generated by Django 6.0.2 on 2026-03-23 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('lehenga', 'Lehenga'), ('kurti', 'Kurti'), ('saree', 'Saree'), ('gown', 'Gown'), ('kurta', 'Kurta'), ('sherwani', 'Sherwani'), ('shirt', 'Shirt'), ('trouser', 'Trouser')], default='kurti', max_length=20),
        ),
    ]
